app:
  frontend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-frontend
      tag: ddb2e86fd9350f101323446a5a140f5b083e52fa
    service:
      type: LoadBalancer
      port: 80
    ingress:
      enabled: true
      host:
      path: /
      pathType: Prefix
  backend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-backend
      tag: ddb2e86fd9350f101323446a5a140f5b083e52fa
    service:
      type: ClusterIP
      port: 8888
  db:
    replicaCount: 1
    image:
      repo: mongo
      tag: latest
    service:
      type: ClusterIP
      port: 27017

