app:
  frontend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-frontend
      tag: c1b07c20defde8caccc612e0fa691bf093ed3298
    service:
      type: LoadBalancer
      port: 80
    ingress:
      enabled: true
      host:
      path: /
      pathType: Prefix
  backend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-backend
      tag: c1b07c20defde8caccc612e0fa691bf093ed3298
    service:
      type: ClusterIP
      port: 8888
  db:
    replicaCount: 1
    image:
      repo: mongo
      tag: latest
    service:
      type: ClusterIP
      port: 27017

