app:
  frontend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-frontend
      tag: 3dd90f17b37de604454a339b218a87500a7d59e8
    service:
      type: LoadBalancer
      port: 80
    ingress:
      enabled: true
      host: frontend.example.com
      path: /
      pathType: Prefix
  backend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-backend
      tag: 3dd90f17b37de604454a339b218a87500a7d59e8
    service:
      type: ClusterIP
      port: 8888
  db:
    replicaCount: 1
    image:
      repo: mongo
      tag: 3dd90f17b37de604454a339b218a87500a7d59e8
    service:
      type: ClusterIP
      port: 27017

