app:
  frontend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-frontend
      tag: 40b95d00eb96ede242f160ef066c1c6c686644fc
    service:
      type: LoadBalancer
      port: 80
    ingress:
      enabled: true
      host:
      path: /
      pathType: Prefix
  backend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-backend
      tag: 40b95d00eb96ede242f160ef066c1c6c686644fc
    service:
      type: ClusterIP
      port: 8888
  db:
    replicaCount: 1
    image:
      repo: mongo
      tag: latest
    service:
      type: ClusterIP
      port: 27017

