app:
  frontend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-frontend
      tag: 99db7ef76e87de68ba6ce9159ae8bad4af9e6adc
    service:
      type: LoadBalancer
      port: 80
    ingress:
      enabled: true
      host: frontend.example.com
      path: /
      pathType: Prefix
  backend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-backend
      tag: 99db7ef76e87de68ba6ce9159ae8bad4af9e6adc
    service:
      type: ClusterIP
      port: 8888
  db:
    replicaCount: 1
    image:
      repo: mongo
      tag: latest
    service:
      type: ClusterIP
      port: 27017

