app:
  frontend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-frontend
      tag: 740f2656dc3596d6de33d81b35f8999c210f5c52
    service:
      type: LoadBalancer
      port: 80
    ingress:
      enabled: true
      host: frontend.example.com
      path: /
      pathType: Prefix
  backend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-backend
      tag: 740f2656dc3596d6de33d81b35f8999c210f5c52
    service:
      type: ClusterIP
      port: 8888
  db:
    replicaCount: 1
    image:
      repo: mongo
      tag: 740f2656dc3596d6de33d81b35f8999c210f5c52
    service:
      type: ClusterIP
      port: 27017

