app:
  frontend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-frontend
      tag: a0fb346aaad431be9db897253b31002d1d3f8519
    service:
      type: LoadBalancer
      port: 80
    ingress:
      enabled: true
      host:
      path: /
      pathType: Prefix
    deployment:
      revisionHistoryLimit: 0
  backend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-backend
      tag: a0fb346aaad431be9db897253b31002d1d3f8519
    service:
      type: ClusterIP
      port: 8888
    deployment:
      revisionHistoryLimit: 0
  db:
    replicaCount: 1
    image:
      repo: mongo
      tag: latest
    service:
      type: ClusterIP
      port: 27017
    deployment:
      revisionHistoryLimit: 0
