app:
  frontend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-frontend
      tag: 675ffe59c774fdb1727352ffa2acbe41fa7c20ca
    service:
      type: LoadBalancer
      port: 80
    ingress:
      enabled: true
      host:
      path: /
      pathType: Prefix
    deployment:
      revisionHistoryLimit: 0
  backend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-backend
      tag: 675ffe59c774fdb1727352ffa2acbe41fa7c20ca
    service:
      type: ClusterIP
      port: 8888
    deployment:
      revisionHistoryLimit: 0
  db:
    replicaCount: 1
    image:
      repo: mongo
      tag: latest
    service:
      type: ClusterIP
      port: 27017
    deployment:
      revisionHistoryLimit: 0
