app:
  frontend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-frontend
      tag: 380d79334bad8428e89e3dc18331d9320ff96bed
    service:
      type: LoadBalancer
      port: 80
    ingress:
      enabled: true
      host:
      path: /
      pathType: Prefix
    deployment:
      revisionHistoryLimit: 0
  backend:
    replicaCount: 1
    image:
      repo: ghcr.io/benedict-cs/k8s-hw3-backend
      tag: 380d79334bad8428e89e3dc18331d9320ff96bed
    service:
      type: ClusterIP
      port: 8888
    deployment:
      revisionHistoryLimit: 0
  db:
    replicaCount: 1
    image:
      repo: mongo
      tag: latest
    service:
      type: ClusterIP
      port: 27017
    deployment:
      revisionHistoryLimit: 0
